# Generated by Django 4.2 on 2024-01-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('top', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('used', models.PositiveIntegerField(default=0)),
                ('model_class', models.CharField(blank=True, max_length=10, null=True)),
                ('year_from', models.SmallIntegerField(blank=True, null=True)),
                ('year_to', models.SmallIntegerField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.brand')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doors_count', models.SmallIntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=60, null=True)),
                ('notice', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'configuraton',
            },
        ),
        migrations.CreateModel(
            name='Modification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offers_price_from', models.BigIntegerField(default=0)),
                ('offers_price_to', models.BigIntegerField(default=0)),
                ('group_name', models.CharField(blank=True, max_length=100, null=True)),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.configuration')),
            ],
            options={
                'db_table': 'modification',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horse_power', models.FloatField(blank=True, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission', models.CharField(blank=True, max_length=100, null=True)),
                ('drive', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.FloatField(default=0)),
                ('time_to_100', models.FloatField(default=0)),
                ('max_speed', models.SmallIntegerField(default=0)),
                ('diameter', models.FloatField(default=0)),
                ('petrol_type', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('width', models.FloatField(default=0)),
                ('length', models.FloatField(default=0)),
                ('fuel_tank_capacity', models.FloatField(default=0)),
                ('volume_litres', models.FloatField(default=0)),
                ('safety_rating', models.FloatField(default=0)),
                ('safety_grade', models.FloatField(default=0)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.modification')),
            ],
            options={
                'db_table': 'specifications',
            },
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electro_mirrors', models.BooleanField(default=True)),
                ('airbag_side', models.BooleanField(default=True)),
                ('hatch', models.BooleanField(default=True)),
                ('led_light', models.BooleanField(default=True)),
                ('rain_sensor', models.BooleanField(default=True)),
                ('aux', models.BooleanField(default=True)),
                ('modification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.modification')),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year_start', models.SmallIntegerField(blank=True, null=True)),
                ('year_stop', models.SmallIntegerField(blank=True, null=True)),
                ('isrestyle', models.BooleanField(blank=True, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.carmodel')),
            ],
            options={
                'db_table': 'generation',
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='generation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.generation'),
        ),
    ]
