# Generated by Django 4.2 on 2024-01-04 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_country_brand_cyrillic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='api_brand_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='api_configuration_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
