# Generated by Django 4.2 on 2024-01-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_brand_api_brand_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='api_model_id',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='api_generation_id',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
