# Generated by Django 4.2 on 2024-01-04 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_carmodel_api_model_id_generation_api_generation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='modification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.modification'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='modification',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cars.modification'),
        ),
    ]
