# Generated by Django 4.2 on 2024-01-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_options_modification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modification',
            name='api_modification_id',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
