# Generated by Django 4.2 on 2024-01-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_modification_api_modification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modification',
            name='offers_price_from',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='modification',
            name='offers_price_to',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
